### ISSUE TITLE
Breaking change to primary header filename not mentioned in release notes

### ISSUE THREAD

**Issue by per1234** [arduino-libraries/Arduino_USBHostMbed5#17]
The primary header filename was changed from `USBHostMbed5.h` to `Arduino_USBHostMbed5.h` in the 0.0.3 release:

https://github.com/arduino-libraries/Arduino_USBHostMbed5/commit/c3182e90de6ee60ae50619fbd80c30f4fc1f6a39

This is a breaking change. Frequent breaking changes should be expected by the user of any project that is still in the unstable development phase, as [indicated by the use of the the `0` major version series](https://semver.org/#spec-item-4), however, it is still best practices to communicate about breaking changes even during that development phase.

No communication of the breaking change was made in the 0.0.3 release notes:

https://github.com/arduino-libraries/Arduino_USBHostMbed5/releases/tag/0.0.3

---

Originally reported at https://forum.arduino.cc/t/usb-host-keyboard-example-from-arduino-hidhost-library-not-found/1102876/10

**Comment by aentinger** [comment]
Done, see here: https://github.com/arduino-libraries/Arduino_USBHostMbed5/releases/tag/0.0.3
