### ISSUE TITLE
USBHostSerial Example

### ISSUE THREAD

**Issue by andualemt** [arduino-libraries/Arduino_USBHostMbed5#19]
I have been trying to get USB Host serial class to work with my USB device. I can connect the device to my computer and read/write commands via virtual COM port. I am using the Arduino Portneta Machine controller. Can you please give an example?

**Comment by aentinger** [comment]
There should be one now, see #18 .

**Comment by manchoz** [comment]
Actually, #18 uses the RS485 port to print out debugging info when printing over `Serial` (because the USB port is already in use, e.g. on the Opta) is not possible.
